//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcstock1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class selling
    {
        public int SELLINGID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<int> NUMBER { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual products products { get; set; }
    }
}
